### PR TITLE
Enable multi selection on listbox

### PR DESCRIPTION
**Pull request by ktye**
This enables multiple selections on listbox.
However I don't know how to enable it selectively (single-selection or multi-selection).

The current implementation of NewListBox does not allow to pass arguments, besides the parent widget.
In this CL I tried to add a method SetMultiSelection which changes the listbox after creation.
However, this has no effect.

Do you have a proposal how to enable it selectively?

### CODE REVIEW

**Comment by lxn** [comment]
Most people use the declarative interface and so probably wouldn't be offended too much by a `NewListBoxWithStyle` constructor function, which would be called from `declarative/ListBox`, similar to `NewTableViewWithStyle`.

`TableView` also has the concept of single or multiple selection with methods like `SingleItemSelection` and `SelectedIndexes`. Probably we should try to make the interface the same. The question is if the existing interface in `TableView` should be changed. (That `IndexList` type is kind of pathetic.)

I would prefer both `ListBox` and `TableView` to default to single selection and have these methods:
```Go
MultiSelection() bool
SetMultiSelection(multiSel bool) /*error?*/ // TableView only
SelectedIndexes() []int
SetSelectedIndexes(indexes []int) /*error?*/
SelectedIndexesChanged() *Event
```
Most of the time I have tried to avoid breaking changes, but then again I have never promised any stability either.

BTW. In situations like your `SetMultiSelection`, you could just call `lb.ensureStyleBits(win.LBS_EXTENDEDSEL, multisel)`

**Comment by ktye** [comment]
For the time being, I made the changes compatible to TableView, so for now, SingleSelection is false by default.
This is currently implemented for listbox:
```go
SelectedIndexes() []int
SetSelectedIndexes(indexes []int)
```
I don't know if the event
```go
SelectedIndexesChanged() *Event
```
is necessary, as CurrentIndexChanged can be used for both cases.

I did not implement 
```go
MultiSelection() bool
```
either. Do you think this is useful? It cannot be changed dynamically, so you should know wether you created a single or multi-selection listbox anyway.

I also added horizontal scrolling (the scrollbar is shown only if it's necessary).

If you prefer, I can change to the interface you suggested making SingleSelection the default.
You have to decide.

**Comment by lxn** [comment]
Just pushed `TableView` changes.

Please adapt your additions to `ListBox` accordingly. I'm fine leaving out `MultiSelection`, but would prefer having `SelectedIndexesChanged`.

**Comment by ktye** [comment]
I changed the default to MultiSelection (false) and added SelectedIndexesChanged.

**Comment by lxn** [comment]
Thanks!

**Pull request merged**
