### PR TITLE
mainloop: add optional C implementation

### PR DESCRIPTION
**Pull request by zx2c4**
Performance!

### CODE REVIEW

**Comment by lxn** [comment]
Just noticed this doesn't work without mingw installed:
`exec: "gcc": executable file not found in %PATH%`

**Comment by zx2c4** [comment]
Usually it only searches for it when CGO_ENABLED=1 is set.

**Comment by kjk** [comment]
CGO_ENABLED=1 seems to be the default setting on Windows (according to `go env`).

This wouldn't be a problem if it used a different build tag to enable it so that you can opt-in but it's not the default.

**Comment by zx2c4** [comment]
Would you investigate and figure out which build tag isn't enabled by default that cgo enables?

**Comment by kjk** [comment]
Not sure I understand.

You can pick arbitrary build tag, say `enable_c_msgloop` and put C code with `// +build enable_c_msgloop` and pure Go code with `// +build !enable_c_msgloop`.

Then people writing apps can opt-in by building with `go build -tags enable_c_msgloop` but by default, they would get the pure Go implementation.

**Comment by zx2c4** [comment]
Oh, like that. Shucks. I was hoping that there'd be something we could use that would indicate the user has opted in to cgo elsewhere -- like including it in their project somewhere.

If this doesn't exist then indeed we'll have to change the cgo build tag I've used into something more specific. `walk_use_cgo` or something. If you can't find any better alternative than that, feel free to send a PR that changes the build tag to something different and documents it in the README.md, and I'll be fine with that.

**Comment by zx2c4** [comment]
Oh, never mind, this was reverted. So I'll resubmit.

**Pull request merged**
